Fix error with reverse foreign key in Django 4.1
There's [a breaking change](https://docs.djangoproject.com/en/dev/releases/4.1/#reverse-foreign-key-changes-for-unsaved-model-instances) in Django 4.1:

> In order to unify the behavior with many-to-many relations for unsaved model instances, a reverse foreign key now raises ValueError when calling related managers for unsaved objects.

That was the cause of this, when running tests like
`tests.events.test_models.EventStrTestCase.test_with_no_title_many_works`:

> ValueError: 'Event' instance needs to have a primary key value before this relationship can be used.

It was this line in `Event.make_title()`:

	work_titles = [str(sel.work.title) for sel in self.work_selections.all()]

So now we only look at those relationships if the event has a PK.